[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'cloud-event-transforms'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Cloud event transforms'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

[Logging]
EnableRemote = false
File = './logs/cloud-event-transforms.log'

[Binding]
Type="http"
